---
title: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(tidyr)
library(gridExtra)
library(parallel)
library(ggplot2)
library(matrixStats)
library(patchwork)
set.seed(2)
```

```{r}
# meanTop<-function(v){mean(v[1:10])}
marPar<-function(l){
  sum(l[[1]]*(l[[2]])/sum(l[[2]]))
}
```

```{r}
myDataLoad<-function(fname,sim=200){
  pic=data.frame()
  for (k in 1:sim){
      load(paste(fname,k,".Rda",sep=""))
      d=data.frame(k_b=sapply(mm,"[[","k_b"),
                   k_c=sapply(mm,"[[","k_c"),
                   w_c=sapply(mm,"[[","w_c"),
                   mu=sapply(mm,"[[","mu"),
                   sigm=sapply(mm,"[[","sigm"),
                   G1=sapply(mm,"[[","G1"),
                   G0=sapply(mm,"[[","G0")
                   ) %>%
      mutate(ratio=G1-G0)
      pic=rbind(pic,d)
  }
  pic
}
```


#data point
```{r}
myNumPlot<-function(pic){
  pic %>% 
  group_by(k_c,k_b)%>%
  dplyr::summarise(ratio=mean(ratio))%>%
  mutate(k_b=factor(k_b))%>%
  ggplot(aes(x=k_c,y=ratio,color=k_b))+
  geom_line(linewidth=1)+
  geom_point()+
  scale_y_continuous(limits = c(-2,7.8),breaks = c(-2,0,2,4,6))+
  scale_colour_grey(start = 0.1,end = 0.8,
                    labels=c(expression(k[b]*"=1"),expression(k[b]*"=3"),expression(k[b]*"=5")))+
  geom_hline(yintercept = 0,linetype="dashed")+
  ylab("Log-likelihood Ratio")+
  xlab("Number of Cause Events")+
  labs(colour="Number of Base Rate Effects")+
  theme_classic()+
  theme(legend.position = c(0.15,0.8),
    axis.text=element_text(size=14),
    plot.title = element_text(size = 16,hjust = 0.5, face = "bold"),
    axis.title = element_text(size=14),
    legend.title=element_blank(),
    legend.text=element_text(size=12),
    legend.background = element_rect(fill='transparent'),
    legend.text.align = 0)
}


pic=myDataLoad("sim/num_")
pic2=myDataLoad("sim_poi/num_")

p1= myNumPlot(pic)+ ggtitle("Event-based")
p2=myNumPlot(pic2)+ ggtitle("Event-based")

p1|p2

# ggsave(file="f_datapoint.pdf",width = 10,height = 4)
```

```{r}
myDelayPlot<-function(pic){
  pic %>% 
  group_by(mu,w_c)%>%
  dplyr::summarise(ratio=mean(ratio))%>%
  mutate(w_c=factor(w_c,levels=c(1,0.8,0.6)))%>%
  ggplot(aes(x=mu,y=ratio,color=w_c))+
  geom_line(linewidth=1)+
  geom_point()+
  scale_colour_grey(start = 0.1,end = 0.8,labels=c(expression(w[c]*"=1"),expression(w[c]*"=0.8"),expression(w[c]*"=0.6")))+ 
  theme_classic()+
  ylab("Log-likelihood Ratio")+
  xlab("Causal Delay")+
  theme(legend.position = c(0.8,0.8),
      axis.text=element_text(size=12),
      axis.title = element_text(size=14),
      plot.title = element_text(size = 16,face = "bold",hjust = 0.05),
      legend.title=element_blank(),
      legend.text=element_text(size=12),
      legend.background = element_rect(fill='transparent'),
      legend.text.align = 0)
}

myDelayPlotS1<-function(pic){
  pic %>% 
  group_by(mu,w_c)%>%
  dplyr::summarise(G1=mean(G1))%>%
  mutate(w_c=factor(w_c,levels=c(1,0.8,0.6)))%>%
  ggplot(aes(x=mu,y=G1,color=w_c))+
  geom_line(linewidth=1)+
  geom_point()+
  scale_colour_grey(start = 0.1,end = 0.8,labels=c(expression(w[c]*"=1"),expression(w[c]*"=0.8"),expression(w[c]*"=0.6")))+ #
  # geom_hline(yintercept = 0,linetype="dashed")+
  theme_classic()+
  ylab("Log-likelihood of S1")+
  xlab("Causal Delay")+
  theme(legend.position = "none",
      axis.text=element_text(size=12),
      axis.title = element_text(size=14),
      legend.title=element_blank(),
      legend.text=element_text(size=12),
      legend.background = element_rect(fill='transparent'),
      legend.text.align = 0)
}

pic=myDataLoad("sim/delay_")
pic2=myDataLoad("sim_poi/delay_")

p1= myDelayPlot(pic) +ggtitle("Event-based")
p2=myDelayPlotS1(pic)+  scale_y_continuous(limits = c(-36,-27.5))
p3= myDelayPlot(pic2) +ggtitle("Rate-based")
p4=myDelayPlotS1(pic2)+    scale_y_continuous(limits = c(-55,-40))


p1|p2|p3|p4
```

#delay Range
```{r}
myVaryPlot<-function(pic){
  pic %>% 
  group_by(sigm,mu)%>%
  dplyr::summarise(ratio=mean(ratio))%>%
  mutate(mu=factor(mu))%>%
  ggplot(aes(x=sigm,y=ratio,color=mu))+
  geom_line(linewidth=1)+
  geom_point()+
  # scale_y_continuous(limits = c(-2,6),breaks = c(-2,0,2,4,6))+
  scale_x_continuous(breaks = c(1,3,5,7,9))+
  scale_colour_grey(start = 0.1,end = 0.8,labels=c(expression(m[u]*"=10"),expression(m[u]*"=20"),expression(m[u]*"=30")))+
  theme_classic()+
  ylab("Log-likelihood Ratio")+
  xlab("Delay Range")+
  theme(legend.position = c(0.8,0.8),
      axis.text=element_text(size=12),
      axis.title = element_text(size=14),
      plot.title = element_text(size = 16,face = "bold",hjust = 0.05),
      legend.title=element_blank(),
      legend.text=element_text(size=12),
      legend.background = element_rect(fill='transparent'),
      legend.text.align = 0)
}

myVaryPlotS1<-function(pic){
  pic %>% 
  group_by(sigm,mu)%>%
  dplyr::summarise(G1=mean(G1))%>%
  mutate(mu=factor(mu))%>%
  ggplot(aes(x=sigm,y=G1,color=mu))+
  geom_line(linewidth=1)+
  geom_point()+
  # scale_y_continuous(limits = c(-2,6),breaks = c(-2,0,2,4,6))+
  scale_x_continuous(breaks = c(1,3,5,7,9))+
  scale_colour_grey(start = 0.1,end = 0.8,labels=c(expression(mu*"=10"),expression(mu*"=20"),expression(mu*"=30")))+
  theme_classic()+
  ylab("Log-likelihood of S1")+
  xlab("Delay Range")+
  theme(legend.position = "none",
      axis.text=element_text(size=12),
      axis.title = element_text(size=14),
      legend.title=element_blank(),
      legend.text=element_text(size=12),
      legend.background = element_rect(fill='transparent'),
      legend.text.align = 0)
}

pic=myDataLoad("sim/vary_")
pic2=myDataLoad("sim_poi/vary_")

p5= myVaryPlot(pic) +ggtitle("Event-based")
p6=myVaryPlotS1(pic)# +  scale_y_continuous(limits = c(-36,-27.5))
p7= myVaryPlot(pic2) +ggtitle("Rate-based")
p8=myVaryPlotS1(pic2)+ scale_y_continuous(breaks = seq(-46,-56,-2))

(p1|p2|p3|p4)/(p5|p6|p7|p8)

ggsave(file="f_delayvary.pdf",width = 14,height = 7)
```

#expectation
```{r}
myExpPlot<-function(pic){
  pic %>% 
  group_by(k_c,model)%>%
  dplyr::summarise(ratio=mean(ratio))%>%
  ggplot(aes(x=k_c,y=ratio,fill=model))+
  geom_bar(stat = "identity",color="black")+ #,position=position_dodge(.0)
  xlab("Number of Cause Events")+
  ylab(expression("Log-likelihood Ratio "*(S[s]/S[l])) )+
  scale_fill_grey(start = 0.9,end = 0.6,labels=c("Short Prior","Long Prior"))+
  theme_classic()+
  theme(legend.position = c(0.2,0.9),
      axis.text=element_text(size=12),
      axis.title = element_text(size=14),
      legend.title=element_blank(),
      plot.title = element_text(size = 16,face = "bold",hjust = 0.5),
      legend.text=element_text(size=12),
      legend.background = element_rect(fill='transparent'),
      legend.text.align = 0)
  
}
```




```{r}
pic1=myDataLoad("sim/exp10_",sim=20)
pic11=pic1 %>%subset(mu==10)
pic12=pic1 %>%subset(mu==20)
pic1=pic11 %>% select(k_b,k_c,w_c,sigm) %>%
  mutate(ratio=pic11$G1-pic12$G1,model="exp10")

pic2=myDataLoad("sim/exp20_",sim=20)
pic21=pic2 %>%subset(mu==10)
pic22=pic2 %>%subset(mu==20)
pic2=pic21 %>% select(k_b,k_c,w_c,sigm) %>%
  mutate(ratio=pic21$G1-pic22$G1,model="exp20")


picE=rbind(pic1,pic2)

pic1=myDataLoad("sim_poi/exp10_",sim=20)
pic11=pic1 %>%subset(mu==10)
pic12=pic1 %>%subset(mu==20)
pic1=pic11 %>% select(k_b,k_c,w_c,sigm) %>%
  mutate(ratio=pic11$G1-pic12$G1,model="exp10")

pic2=myDataLoad("sim_poi/exp20_",sim=20)
pic21=pic2 %>%subset(mu==10)
pic22=pic2 %>%subset(mu==20)
pic2=pic21 %>% select(k_b,k_c,w_c,sigm) %>%
  mutate(ratio=pic21$G1-pic22$G1,model="exp20")

picR=rbind(pic1,pic2)
```

```{r}
p1=picE %>% myExpPlot() + 
  scale_x_continuous(breaks = c(1:5))+
  scale_y_continuous(limits = c(-10,15))+
  ggtitle("Event-based")
p2=picR %>% myExpPlot() + 
  scale_x_continuous(breaks = seq(2,10,2))+
  scale_y_continuous(limits = c(-10,15))+
  ggtitle("Rate-based")

p1|p2

ggsave(file="f_delayexp.pdf",width = 9,height = 4)
```






```{r}
# data.frame(time=seq(1,20,length.out=100))%>%
#   mutate(mu=dgamma(time,100,10))%>%
#   ggplot(aes(x=time,y=mu))+
#   geom_line()
# 
# data.frame(time=seq(1,20,length.out=100))%>%
#   mutate(mu=dgamma(time,400,20))%>%
#   ggplot(aes(x=time,y=mu))+
#   geom_line()
```



```{r}
# pic1=data.frame()
# for (k in 1:sim){
#     load(paste("sim/delay_",k,".Rda",sep=""))
#     d=data.frame(mu=sapply(mm,"[[","mu"),
#                  w_c=sapply(mm,"[[","w_c"),
#                  G1=sapply(mm,"[[","G1"),
#                  G0=sapply(mm,"[[","G0"),
#                  power=sapply(sapply(mm,"[[","par1")[c("c_p"),],"[[",1)
#                  )
#     pic1=rbind(pic1,d)
# }

# pic1 %>%
#   group_by(mu,w_c)%>%
#   dplyr::summarise(power=mean(power))%>%
#   mutate(w_c=factor(w_c,levels=c(1,0.8,0.6)))%>%
#   ggplot(aes(x=mu,y=power,color=w_c))+
#   geom_line(linewidth=1)+
#   geom_point()+
#   # scale_y_continuous(limits = c(-2,6),breaks = c(-2,0,2,4,6))+
#   scale_colour_grey(start = 0.1,end = 0.8,labels=c(expression(w[c]*"=1"),expression(w[c]*"=0.8"),expression(w[c]*"=0.6")))+ #
#   # geom_hline(yintercept = 0,linetype="dashed")+
#   theme_classic()+
#   ylab("Causal Power")+
#   xlab("Causal Delay")+
#   theme(legend.position = c(0.8,0.8),
#       axis.text=element_text(size=14),
#       axis.title = element_text(size=14),
#       legend.title=element_blank(),
#       legend.text=element_text(size=12),
#       legend.background = element_rect(fill='transparent'),
#       legend.text.align = 0)


# pic %>%
#   group_by(mu,w_c)%>%
#   dplyr::summarise(G1=mean(G1),G0=mean(G0))%>%
#   mutate(w_c=factor(w_c,levels=c(1,0.8,0.6)))%>%
#   pivot_longer(cols = c("G1","G0"),names_to = "str",values_to = "logli")%>%
#   ggplot(aes(x=mu,y=logli,color=w_c,linetype=str))+
#   geom_line(linewidth=1)+
#   geom_point()+
#   # scale_y_continuous(limits = c(-2,6),breaks = c(-2,0,2,4,6))+
#   scale_colour_grey(start = 0.1,end = 0.8,labels=c(expression(w[c]*"=1"),expression(w[c]*"=0.8"),expression(w[c]*"=0.6")))+ #
#   # geom_hline(yintercept = 0,linetype="dashed")+
#   theme_classic()+
#   ylab("Log-likelihood Ratio")+
#   xlab("Causal Delay")+
#   theme(legend.position = c(0.8,0.8),
#       axis.text=element_text(size=14),
#       axis.title = element_text(size=14),
#       legend.title=element_blank(),
#       legend.text=element_text(size=12),
#       legend.background = element_rect(fill='transparent'),
#       legend.text.align = 0)
```

